// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservasTemporales.Data;

#nullable disable

namespace src.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827194820_InitialSeedInmuebles")]
    partial class InitialSeedInmuebles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ReservasTemporales.Models.Inmueble", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Coord")
                        .HasColumnType("longtext");

                    b.Property<int>("Cupo")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FotoPortada")
                        .HasColumnType("longtext");

                    b.Property<string>("Fotos")
                        .HasColumnType("longtext");

                    b.Property<int>("IdPropietario")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPropietario");

                    b.ToTable("Inmuebles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Coord = "-34.6037,-58.3816",
                            Cupo = 4,
                            Direccion = "Av. Corrientes 1234, CABA",
                            IdPropietario = 1,
                            Precio = 45000.00m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Coord = "-34.9214,-57.9545",
                            Cupo = 6,
                            Direccion = "Calle 50 #432, La Plata",
                            IdPropietario = 2,
                            Precio = 75000.00m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Coord = "-41.1335,-71.3103",
                            Cupo = 5,
                            Direccion = "Ruta 40 Km 12, Bariloche",
                            IdPropietario = 3,
                            Precio = 120000.00m,
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("ReservasTemporales.Models.Inquilino", b =>
                {
                    b.Property<int>("IdInquilino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdInquilino"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdInquilino");

                    b.ToTable("Inquilino");

                    b.HasData(
                        new
                        {
                            IdInquilino = 1,
                            Activo = true,
                            Apellido = "Morales",
                            Dni = "38123456",
                            Email = "fede.morales@gmail.com",
                            Nombre = "Federico",
                            Telefono = "1199887766"
                        },
                        new
                        {
                            IdInquilino = 2,
                            Activo = true,
                            Apellido = "Sosa",
                            Dni = "40987654",
                            Email = "gaby.sosa@live.com",
                            Nombre = "Gabriela",
                            Telefono = "1188776655"
                        },
                        new
                        {
                            IdInquilino = 3,
                            Activo = true,
                            Apellido = "Sosa",
                            Dni = "45975677",
                            Email = "lucia.sosa@gmail.com",
                            Nombre = "Lucía",
                            Telefono = "1198784675"
                        });
                });

            modelBuilder.Entity("ReservasTemporales.Models.Propietario", b =>
                {
                    b.Property<int>("IdPropietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPropietario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdPropietario");

                    b.ToTable("Propietario");

                    b.HasData(
                        new
                        {
                            IdPropietario = 1,
                            Activo = true,
                            Apellido = "Fernández",
                            Dni = "25111222",
                            Email = "alberto.f@gmail.com",
                            Nombre = "Alberto",
                            Telefono = "1144556677"
                        },
                        new
                        {
                            IdPropietario = 2,
                            Activo = true,
                            Apellido = "López",
                            Dni = "28333444",
                            Email = "beatriz_lopez@hotmail.com",
                            Nombre = "Beatriz",
                            Telefono = "1133221100"
                        },
                        new
                        {
                            IdPropietario = 3,
                            Activo = true,
                            Apellido = "García",
                            Dni = "31555666",
                            Email = "cgarcia@yahoo.com",
                            Nombre = "Claudio",
                            Telefono = "1166778899"
                        });
                });

            modelBuilder.Entity("ReservasTemporales.Models.Inmueble", b =>
                {
                    b.HasOne("ReservasTemporales.Models.Propietario", "Propietario")
                        .WithMany()
                        .HasForeignKey("IdPropietario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propietario");
                });
#pragma warning restore 612, 618
        }
    }
}
