// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservasTemporales.Data;

#nullable disable

namespace src.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903190842_CambiarTablasASingular")]
    partial class CambiarTablasASingular
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ReservasTemporales.Models.Inmueble", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Coord")
                        .HasColumnType("longtext");

                    b.Property<int>("Cupo")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FotoPortada")
                        .HasColumnType("longtext");

                    b.Property<string>("Fotos")
                        .HasColumnType("longtext");

                    b.Property<int>("IdPropietario")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPropietario");

                    b.ToTable("Inmueble", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Coord = "-34.6037,-58.3816",
                            Cupo = 4,
                            Direccion = "Av. Corrientes 1234, CABA",
                            IdPropietario = 1,
                            Precio = 45000.00m,
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Coord = "-34.9214,-57.9545",
                            Cupo = 6,
                            Direccion = "Calle 50 #432, La Plata",
                            IdPropietario = 2,
                            Precio = 75000.00m,
                            Tipo = 0
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Coord = "-41.1335,-71.3103",
                            Cupo = 5,
                            Direccion = "Ruta 40 Km 12, Bariloche",
                            IdPropietario = 3,
                            Precio = 120000.00m,
                            Tipo = 2
                        });
                });

            modelBuilder.Entity("ReservasTemporales.Models.Inquilino", b =>
                {
                    b.Property<int>("IdInquilino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdInquilino"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdInquilino");

                    b.ToTable("Inquilino", (string)null);

                    b.HasData(
                        new
                        {
                            IdInquilino = 1,
                            Activo = true,
                            Apellido = "Morales",
                            Dni = "38123456",
                            Email = "fede.morales@gmail.com",
                            Nombre = "Federico",
                            Telefono = "1199887766"
                        },
                        new
                        {
                            IdInquilino = 2,
                            Activo = true,
                            Apellido = "Sosa",
                            Dni = "40987654",
                            Email = "gaby.sosa@live.com",
                            Nombre = "Gabriela",
                            Telefono = "1188776655"
                        },
                        new
                        {
                            IdInquilino = 3,
                            Activo = true,
                            Apellido = "Sosa",
                            Dni = "45975677",
                            Email = "lucia.sosa@gmail.com",
                            Nombre = "Lucia",
                            Telefono = "1198784675"
                        });
                });

            modelBuilder.Entity("ReservasTemporales.Models.Propietario", b =>
                {
                    b.Property<int>("IdPropietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPropietario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdPropietario");

                    b.ToTable("Propietario", (string)null);

                    b.HasData(
                        new
                        {
                            IdPropietario = 1,
                            Activo = true,
                            Apellido = "Fernandez",
                            Dni = "25111222",
                            Email = "alberto.f@gmail.com",
                            Nombre = "Alberto",
                            Telefono = "1144556677"
                        },
                        new
                        {
                            IdPropietario = 2,
                            Activo = true,
                            Apellido = "Lopez",
                            Dni = "28333444",
                            Email = "beatriz_lopez@hotmail.com",
                            Nombre = "Beatriz",
                            Telefono = "1133221100"
                        },
                        new
                        {
                            IdPropietario = 3,
                            Activo = true,
                            Apellido = "Garcia",
                            Dni = "31555666",
                            Email = "cgarcia@yahoo.com",
                            Nombre = "Claudio",
                            Telefono = "1166778899"
                        });
                });

            modelBuilder.Entity("ReservasTemporales.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<int>("CreadoPorUserId")
                        .HasColumnType("int")
                        .HasColumnName("creado_por_user_id");

                    b.Property<DateTime>("FechaDesde")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_desde");

                    b.Property<DateTime>("FechaHasta")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_hasta");

                    b.Property<int>("IdInmueble")
                        .HasColumnType("int")
                        .HasColumnName("id_inmueble");

                    b.Property<int>("IdInquilino")
                        .HasColumnType("int")
                        .HasColumnName("id_inquilino");

                    b.Property<decimal>("MontoDiario")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("monto_diario");

                    b.Property<int?>("TerminadoPorUserId")
                        .HasColumnType("int")
                        .HasColumnName("terminado_por_user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorUserId");

                    b.HasIndex("IdInmueble");

                    b.HasIndex("IdInquilino");

                    b.HasIndex("TerminadoPorUserId");

                    b.ToTable("Reserva", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CreadoPorUserId = 1,
                            FechaDesde = new DateTime(2026, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHasta = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdInmueble = 1,
                            IdInquilino = 1,
                            MontoDiario = 45000.00m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CreadoPorUserId = 1,
                            FechaDesde = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaHasta = new DateTime(2026, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdInmueble = 2,
                            IdInquilino = 2,
                            MontoDiario = 75000.00m
                        });
                });

            modelBuilder.Entity("ReservasTemporales.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("apellido");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext")
                        .HasColumnName("avatar");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellido = "Sistema",
                            Email = "admin@gmail.com",
                            Nombre = "Administrador",
                            NombreUsuario = "admin",
                            Password = "123456",
                            Rol = "admin"
                        });
                });

            modelBuilder.Entity("ReservasTemporales.Models.Inmueble", b =>
                {
                    b.HasOne("ReservasTemporales.Models.Propietario", "Propietario")
                        .WithMany()
                        .HasForeignKey("IdPropietario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("ReservasTemporales.Models.Reserva", b =>
                {
                    b.HasOne("ReservasTemporales.Models.Usuario", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReservasTemporales.Models.Inmueble", "Inmueble")
                        .WithMany("Reservas")
                        .HasForeignKey("IdInmueble")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservasTemporales.Models.Inquilino", "Inquilino")
                        .WithMany()
                        .HasForeignKey("IdInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReservasTemporales.Models.Usuario", "TerminadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("TerminadoPorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("Inmueble");

                    b.Navigation("Inquilino");

                    b.Navigation("TerminadoPorUsuario");
                });

            modelBuilder.Entity("ReservasTemporales.Models.Inmueble", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
