// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservasTemporales.Data;

#nullable disable

namespace src.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ReservasTemporales.Models.Propietario", b =>
                {
                    b.Property<int>("IdPropietario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPropietario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("apellido");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("telefono");

                    b.HasKey("IdPropietario");

                    b.ToTable("Propietario");

                    b.HasData(
                        new
                        {
                            IdPropietario = 1,
                            Activo = true,
                            Apellido = "Fernández",
                            Dni = "25111222",
                            Email = "alberto.f@gmail.com",
                            Nombre = "Alberto",
                            Telefono = "1144556677"
                        },
                        new
                        {
                            IdPropietario = 2,
                            Activo = true,
                            Apellido = "López",
                            Dni = "28333444",
                            Email = "beatriz_lopez@hotmail.com",
                            Nombre = "Beatriz",
                            Telefono = "1133221100"
                        },
                        new
                        {
                            IdPropietario = 3,
                            Activo = true,
                            Apellido = "García",
                            Dni = "31555666",
                            Email = "cgarcia@yahoo.com",
                            Nombre = "Claudio",
                            Telefono = "1166778899"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
